### PR TITLE
Simple modal class hook

### PR DESCRIPTION
**Pull request by SquidwardHill**
CSS class hook for styling the modal without having to publish the views.

### CODE REVIEW

**Comment by ralphjsmit** [comment]
Thank you! Could you also add the classes in the same place to the modal and the slide-over? Then we keep it consistent :)

**Comment by SquidwardHill** [comment]
No problem!

Will do.

**Comment by SquidwardHill** [comment]
Okay, so I added component wrapper + body classes. I feel that this could be further extended for the controls and other elements but wasn't sure how far to take it, so let me know what you prefer.

**Comment by ralphjsmit** [comment]
Thank you! Released in 0.8.15.

**Pull request merged**
